/**
 * Modern entry point for Next.js application using Node 23 native TypeScript support.
 * This file wraps the standalone server.js generated by 'next build'.
 */

const port: number = parseInt(process.env.PORT || '8080', 10);
const hostname: string = process.env.HOSTNAME || '0.0.0.0';

console.log(`[Modern Deployment] Starting server on ${hostname}:${port}...`);
console.log(`[Modern Deployment] Using Node.js ${process.version} with --experimental-strip-types`);

// Import the standalone server generated by Next.js
// @ts-ignore - The file is generated at build time
import './server.js';
